2019-04-25 16:45:06,828 ERROR 2690 [-/127.0.0.1/-/0ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'pme'
    at Handshake.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Protocol._enqueue (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'pme'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 2690
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 17:41:11,527 ERROR 2809 [-/127.0.0.1/-/0ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'pme'
    at Handshake.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Protocol._enqueue (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:118:18)
    at Pool.getConnection (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'pme'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 2809
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 17:57:55,506 ERROR 2818 [-/127.0.0.1/-/46ms POST /api/auth] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'use' in 'where clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: SELECT * FROM `pme_user` WHERE `username` = 'admin' AND `password` = '96e79218965eb72c92a549dd5a330112' AND `use` = 1 LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'use' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `pme_user` WHERE `username` = 'admin' AND `password` = '96e79218965eb72c92a549dd5a330112' AND `use` = 1 LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 2818
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 17:59:05,983 ERROR 2818 [-/127.0.0.1/-/38ms GET /api/article?keywords=&page=1&size=10] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'intro' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: select id,title,author,img,fromto,intro,cat_id,content_id,hot,top,keywords,sorter,update_time from pme_article  order by sorter desc limit 0,10
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'intro' in 'field list'"
sqlState: "42S22"
index: 0
sql: "select id,title,author,img,fromto,intro,cat_id,content_id,hot,top,keywords,sorter,update_time from pme_article  order by sorter desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 2818
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 17:59:31,204 ERROR 2818 [-/127.0.0.1/-/3ms GET /api/article?keywords=&page=1&size=10] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'intro' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: select id,title,author,img,fromto,intro,cat_id,content_id,hot,top,keywords,sorter,update_time from pme_article  order by sorter desc limit 0,10
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'intro' in 'field list'"
sqlState: "42S22"
index: 0
sql: "select id,title,author,img,fromto,intro,cat_id,content_id,hot,top,keywords,sorter,update_time from pme_article  order by sorter desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 2818
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 18:00:31,096 ERROR 2818 [-/127.0.0.1/-/8ms GET /api/article?keywords=&page=1&size=10] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'cat_id' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: select id,title,author,img,fromto,intro,cat_id,content_id,hot,top,keywords,sorter,update_time from pme_article  order by sorter desc limit 0,10
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'cat_id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "select id,title,author,img,fromto,intro,cat_id,content_id,hot,top,keywords,sorter,update_time from pme_article  order by sorter desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 2818
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 18:00:38,951 ERROR 2818 [-/127.0.0.1/-/20ms GET /api/article?keywords=&page=1&size=10] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'cat_id' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: select id,title,author,img,fromto,intro,cat_id,content_id,hot,top,keywords,sorter,update_time from pme_article  order by sorter desc limit 0,10
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'cat_id' in 'field list'"
sqlState: "42S22"
index: 0
sql: "select id,title,author,img,fromto,intro,cat_id,content_id,hot,top,keywords,sorter,update_time from pme_article  order by sorter desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 2818
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 19:02:31,434 ERROR 2818 [-/127.0.0.1/-/19ms POST /api/article] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'intro' doesn't have a default value
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: INSERT INTO `pme_article`(`title`, `cat_id`, `sorter`, `img`, `content_id`) VALUES('fdsafdsa', NULL, 50, '', 1)
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'intro' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `pme_article`(`title`, `cat_id`, `sorter`, `img`, `content_id`) VALUES('fdsafdsa', NULL, 50, '', 1)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_DEFAULT_FOR_FIELDError"
pid: 2818
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 19:03:10,277 ERROR 2818 [-/127.0.0.1/-/6ms POST /api/article] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'intro' doesn't have a default value
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: INSERT INTO `pme_article`(`title`, `cat_id`, `sorter`, `img`, `content_id`) VALUES('fdsafdsa', NULL, 50, '', 2)
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'intro' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `pme_article`(`title`, `cat_id`, `sorter`, `img`, `content_id`) VALUES('fdsafdsa', NULL, 50, '', 2)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_DEFAULT_FOR_FIELDError"
pid: 2818
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 19:03:22,139 ERROR 2818 [-/127.0.0.1/-/3ms POST /api/article] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'intro' doesn't have a default value
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: INSERT INTO `pme_article`(`title`, `cat_id`, `sorter`, `img`, `content_id`) VALUES('fdsafdsa', NULL, 50, '', 3)
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'intro' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `pme_article`(`title`, `cat_id`, `sorter`, `img`, `content_id`) VALUES('fdsafdsa', NULL, 50, '', 3)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_DEFAULT_FOR_FIELDError"
pid: 2818
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-25 19:04:03,223 ERROR 2818 [-/127.0.0.1/-/4ms POST /api/cat] nodejs.ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: '' for column 'banner' at row 1
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: INSERT INTO `pme_cat`(`name`, `sorter`, `banner`, `content_id`) VALUES('rewq', 50, '', 5)
code: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELD"
errno: 1366
sqlMessage: "Incorrect integer value: '' for column 'banner' at row 1"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `pme_cat`(`name`, `sorter`, `banner`, `content_id`) VALUES('rewq', 50, '', 5)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError"
pid: 2818
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-13 23:40:10,887 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 2391932ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-14 00:19:47,586 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 2336678ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-14 02:18:35,003 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 7107397ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-14 02:51:04,305 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 1908595ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-14 03:28:52,052 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 2107764ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-14 04:18:35,741 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 2943645ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-14 06:19:32,442 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 7216663ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-14 08:20:09,288 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 7216829ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-14 09:00:48,789 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 2399658ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-14 10:00:58,439 ERROR 61707 nodejs.ClusterClientNoResponseError: client no response in 3569622ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 61707
hostname: xiaohuangyudeMacBook-Pro.local

