2019-03-15 14:14:46,855 ERROR 49202 [-/127.0.0.1/-/8ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49202
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:15:25,449 ERROR 49202 [-/127.0.0.1/-/2ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49202
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:15:30,915 ERROR 49202 [-/127.0.0.1/-/1ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49202
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:15:42,042 ERROR 49203 [-/127.0.0.1/-/8ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49203
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:15:55,566 ERROR 49211 [-/127.0.0.1/-/7ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49211
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:18:16,730 ERROR 49211 [-/127.0.0.1/-/3ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49211
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:18:52,213 ERROR 49211 [-/127.0.0.1/-/1ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49211
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:19:15,071 ERROR 49227 [-/127.0.0.1/-/7ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49227
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:21:23,790 ERROR 49243 [-/127.0.0.1/-/9ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49243
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:21:42,820 ERROR 49256 [-/127.0.0.1/-/7ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find viewEngine for /Users/xiaohuangyu/work/egg-cms/app/view/frontend/index.html
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:66:5)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: ""
expected: true
operator: "=="
pid: 49256
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-15 14:24:22,678 ERROR 49264 [-/127.0.0.1/-/8ms GET /] nodejs.AssertionError [ERR_ASSERTION]: Can't find ViewEngine "nunjucks"
    at ContextView.[contextView#getViewEngine] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:88:5)
    at ContextView.[contextView#render] (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-view/lib/context_view.js:69:39)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 49264
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-16 16:11:54,251 ERROR 53475 [-/127.0.0.1/-/11ms GET /api/auth] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'pme.user' doesn't exist
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: SELECT * FROM `user` WHERE `username` = 'admin' LIMIT 0, 1
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'pme.user' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT * FROM `user` WHERE `username` = 'admin' LIMIT 0, 1"
name: "ER_NO_SUCH_TABLEError"
pid: 53475
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-16 16:18:58,962 ERROR 53533 [-/127.0.0.1/-/12ms GET /api/auth] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'pme.user' doesn't exist
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: SELECT * FROM `user` WHERE `username` = 'admin' LIMIT 0, 1
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'pme.user' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT * FROM `user` WHERE `username` = 'admin' LIMIT 0, 1"
name: "ER_NO_SUCH_TABLEError"
pid: 53533
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-16 16:56:42,722 ERROR 53718 [-/::1/-/10ms GET /api/auth?username=admin] nodejs.TypeError: ctx.validate is not a function
    at AuthController.index (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/auth.js:8:13)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 53718
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-16 17:17:33,550 ERROR 53809 [-/::1/-/17ms GET /api/auth?username=admin&password=111111&remember=true] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'user' in 'where clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: SELECT * FROM `pme_user` WHERE `username` = 'admin' AND `password` = '96e79218965eb72c92a549dd5a330112' AND `user` = 1 LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'user' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `pme_user` WHERE `username` = 'admin' AND `password` = '96e79218965eb72c92a549dd5a330112' AND `user` = 1 LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 53809
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-16 17:24:54,932 ERROR 53814 [-/::1/-/17ms GET /api/auth?username=fdsa&password=fdsa&remember=true] nodejs.TypeError: Cannot convert undefined or null to object
    at AuthService.find (/Users/xiaohuangyu/work/egg-cms/app/service/admin/auth.js:13:9)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 53814
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-16 17:27:06,373 ERROR 53814 [-/::1/-/3ms GET /api/auth?username=admin&password=1111&remember=true] nodejs.TypeError: Cannot convert undefined or null to object
    at AuthService.find (/Users/xiaohuangyu/work/egg-cms/app/service/admin/auth.js:13:9)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 53814
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-16 20:03:34,306 ERROR 54149 [-/::1/-/7ms GET /api/auth?username=admin&password=111111&remember=true] nodejs.ReferenceError: privateKey is not defined
    at auth (/Users/xiaohuangyu/work/egg-cms/app/middleware/auth.js:6:27)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xframe (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-security/lib/middlewares/xframe.js:7:11)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 54149
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-16 20:16:25,018 ERROR 53734 nodejs.ClusterClientNoResponseError: client no response in 234723ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-cms/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 53734
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-16 20:36:14,848 ERROR 53734 nodejs.ClusterClientNoResponseError: client no response in 1169811ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-cms/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 53734
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 09:30:03,381 ERROR 53734 nodejs.ClusterClientNoResponseError: client no response in 29729805ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-cms/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 53734
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 11:15:31,421 ERROR 53734 nodejs.ClusterClientNoResponseError: client no response in 6327742ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-cms/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 53734
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 15:29:16,103 ERROR 53734 nodejs.ClusterClientNoResponseError: client no response in 15224679ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-cms/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 53734
hostname: xiaohuangyudeMacBook-Pro.local

