2019-03-17 19:34:15,033 ERROR 53734 nodejs.ClusterClientNoResponseError: client no response in 1931044ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-cms/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 53734
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 19:54:14,145 ERROR 53734 nodejs.ClusterClientNoResponseError: client no response in 1159082ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-cms/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 53734
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 20:35:13,953 ERROR 54876 [-/::1/-/28ms POST /api/auth] nodejs.Error: Illegal argument undefined
    at module.exports (/Users/xiaohuangyu/work/egg-cms/node_modules/md5/md5.js:152:13)
    at AuthService.check (/Users/xiaohuangyu/work/egg-cms/app/service/admin/auth.js:22:23)
    at AuthController.create (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/auth.js:15:51)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-cms/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-cms/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/@eggjs/router/lib/router.js:190:18
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 54876
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 20:56:57,306 ERROR 54952 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'user' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: SELECT `id`, `username`, `role`, `sorter`, `user`, `nickname`, `note`, `create_time`, `update_time` FROM `pme_user` WHERE `username` = 'admin'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'user' in 'field list'"
sqlState: "42S22"
index: 0
sql: "SELECT `id`, `username`, `role`, `sorter`, `user`, `nickname`, `note`, `create_time`, `update_time` FROM `pme_user` WHERE `username` = 'admin'"
name: "unhandledRejectionError"
pid: 54952
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 20:58:31,271 ERROR 54960 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'user' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: SELECT `id`, `username`, `role`, `sorter`, `user`, `nickname`, `note`, `create_time`, `update_time` FROM `pme_user` WHERE `username` = 'admin'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'user' in 'field list'"
sqlState: "42S22"
index: 0
sql: "SELECT `id`, `username`, `role`, `sorter`, `user`, `nickname`, `note`, `create_time`, `update_time` FROM `pme_user` WHERE `username` = 'admin'"
name: "unhandledRejectionError"
pid: 54960
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 21:07:49,176 ERROR 54982 nodejs.TypeError: user.toArray is not a function
    at UserController.index (/Users/xiaohuangyu/work/egg-cms/app/controller/admin/api/user.js:17:26)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

pid: 54982
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 22:27:54,202 ERROR 55041 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-cms/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-cms/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-cms/node_modules/co/index.js:54:5
    sql: SELECT * FROM `pme_user` WHERE `where` = `username` = 'admin' AND `columns` IN ('id', 'username', 'role', 'sorter', 'nickname', 'note', 'create_time', 'update_time') LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `pme_user` WHERE `where` = `username` = 'admin' AND `columns` IN ('id', 'username', 'role', 'sorter', 'nickname', 'note', 'create_time', 'update_time') LIMIT 0, 1"
name: "unhandledRejectionError"
pid: 55041
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-17 23:51:50,814 ERROR 54848 nodejs.ClusterClientNoResponseError: client no response in 1293774ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-cms/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 54848
hostname: xiaohuangyudeMacBook-Pro.local

2019-03-18 10:10:41,470 ERROR 54848 nodejs.ClusterClientNoResponseError: client no response in 37130408ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xiaohuangyu/work/egg-cms/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
name: "ClusterClientNoResponseError"
pid: 54848
hostname: xiaohuangyudeMacBook-Pro.local

